/**
 * The drink lineup.
 *
 * MindAR is a PLANAR tracker and a can is a cylinder, so one photo only matches
 * while the can is turned roughly as it was photographed (~±30-40°). Each can
 * therefore carries several photos taken around it, and every one of them
 * resolves back to the same drink.
 *
 * INVARIANT: the MindAR target index is the index into `targetEntries` — the
 * flattened list of every photo of every can, in array order.
 * `scripts/compileTargets.ts` compiles them in exactly that order, so
 * reordering `cans` or a can's `targetImages` without recompiling silently
 * pairs cans with the wrong 3D model. Add new cans and new angles at the END.
 *
 * Photos live in `public/targets/<id>/` so one file serves as both the tracking
 * target (read from disk by the compiler) and the label texture wrapped around
 * the 3D can (fetched by the browser). Set `labelTexture` only if you have a
 * proper flat label unwrap that differs from the tracking photos.
 */

export type Can = {
  /** stable slug, used as a react key and in logs */
  id: string
  /**
   * Photos taken around the can, paths under public/targets (e.g.
   * 'pepsi/wrap-01.jpg'). ALL of them map back to this can. More angles means
   * more rotation coverage and a longer compile — 4 to 6 covers a can well.
   */
  targetImages: string[]
  name: string
  flavour: string
  calories: number
  volumeMl: number
  /** optional override; defaults to the first target image */
  labelTexture?: string
  /** aluminium tint for the top/bottom, and the fallback body colour */
  bodyColor: string
  /**
   * Model height as a multiple of the target image width. MindAR normalises a
   * target's width to 1 unit, so this is how you dial the can to sit exactly
   * on the real one. Start at 1 and tune by eye.
   */
  scale: number
}

/**
 * Each can's images live in their own folder under public/targets/<id>/:
 *   - <id>/label.jpg          a single flat placeholder or photo (scale 1)
 *   - <id>/wrapper.jpg        a flat 360° label unwrap (the labelTexture)
 *   - <id>/wrap-01..NN.jpg    slices of that wrapper, generated by from-wrap
 *
 * The three `placeholder-*` cans ship with the repo so it runs on a fresh clone.
 * Their labels are INVENTED (not real brands), generated by
 * `npm run targets:placeholders`. Display one on a screen or print it to test.
 */
export const cans: Can[] = [
  {
    id: 'placeholder-cola',
    targetImages: ['placeholder-cola/label.jpg'],
    name: 'Cola',
    flavour: 'Original cola',
    calories: 139,
    volumeMl: 330,
    bodyColor: '#c8102e',
    scale: 1
  },
  {
    id: 'placeholder-lemon',
    targetImages: ['placeholder-lemon/label.jpg'],
    name: 'Lemon',
    flavour: 'Lemon & lime',
    calories: 43,
    volumeMl: 330,
    bodyColor: '#0f7b46',
    scale: 1
  },
  {
    id: 'placeholder-orange',
    targetImages: ['placeholder-orange/label.jpg'],
    name: 'Orange',
    flavour: 'Orange',
    calories: 62,
    volumeMl: 330,
    bodyColor: '#e8590c',
    scale: 1
  },
  /**
   * Real cans, generated from a flat 360° label unwrap by
   * `npm run targets:from-wrap <id>/wrapper.jpg <id>`. Each slice is the artwork
   * pre-warped the way a cylinder distorts it, centred 30° apart.
   *
   * scale is 115/66: a slice is exactly one can diameter wide, and MindAR
   * normalises target width to 1 unit, so the can's height is 1.74 of those.
   */
  {
    id: 'coca-cola',
    targetImages: [
      'coca-cola/wrap-01.jpg',
      'coca-cola/wrap-02.jpg',
      'coca-cola/wrap-03.jpg',
      'coca-cola/wrap-04.jpg',
      'coca-cola/wrap-05.jpg',
      'coca-cola/wrap-06.jpg',
      'coca-cola/wrap-07.jpg',
      'coca-cola/wrap-08.jpg',
      'coca-cola/wrap-09.jpg',
      'coca-cola/wrap-10.jpg',
      'coca-cola/wrap-11.jpg',
      'coca-cola/wrap-12.jpg'
    ],
    name: 'Coca-Cola',
    flavour: 'Original cola',
    calories: 139,
    volumeMl: 330,
    labelTexture: 'coca-cola/wrapper.jpg',
    bodyColor: '#c8102e',
    scale: 1.74
  },
  {
    id: 'pepsi',
    targetImages: [
      'pepsi/wrap-01.jpg',
      'pepsi/wrap-02.jpg',
      'pepsi/wrap-03.jpg',
      'pepsi/wrap-04.jpg',
      'pepsi/wrap-05.jpg',
      'pepsi/wrap-06.jpg',
      'pepsi/wrap-07.jpg',
      'pepsi/wrap-08.jpg',
      'pepsi/wrap-09.jpg',
      'pepsi/wrap-10.jpg',
      'pepsi/wrap-11.jpg',
      'pepsi/wrap-12.jpg'
    ],
    name: 'Pepsi',
    flavour: 'Cola',
    calories: 150,
    volumeMl: 355,
    labelTexture: 'pepsi/wrapper.jpg',
    bodyColor: '#004b93',
    scale: 1.74
  },
  {
    id: 'dr-pepper',
    targetImages: [
      'dr-pepper/wrap-01.jpg',
      'dr-pepper/wrap-02.jpg',
      'dr-pepper/wrap-03.jpg',
      'dr-pepper/wrap-04.jpg',
      'dr-pepper/wrap-05.jpg',
      'dr-pepper/wrap-06.jpg',
      'dr-pepper/wrap-07.jpg',
      'dr-pepper/wrap-08.jpg',
      'dr-pepper/wrap-09.jpg',
      'dr-pepper/wrap-10.jpg',
      'dr-pepper/wrap-11.jpg',
      'dr-pepper/wrap-12.jpg'
    ],
    name: 'Dr Pepper',
    flavour: 'Vanilla Float',
    calories: 0,
    volumeMl: 355,
    labelTexture: 'dr-pepper/wrapper.jpg',
    bodyColor: '#7a1518',
    scale: 1.74
  },
  {
    // 500ml can: taller than a 330ml, so scale ≈ 168/66 ≈ 2.55
    id: 'monster-energy',
    targetImages: [
      'monster-energy/wrap-01.jpg',
      'monster-energy/wrap-02.jpg',
      'monster-energy/wrap-03.jpg',
      'monster-energy/wrap-04.jpg',
      'monster-energy/wrap-05.jpg',
      'monster-energy/wrap-06.jpg',
      'monster-energy/wrap-07.jpg',
      'monster-energy/wrap-08.jpg',
      'monster-energy/wrap-09.jpg',
      'monster-energy/wrap-10.jpg',
      'monster-energy/wrap-11.jpg',
      'monster-energy/wrap-12.jpg'
    ],
    name: 'Monster',
    flavour: 'Energy',
    calories: 210,
    volumeMl: 500,
    labelTexture: 'monster-energy/wrapper.jpg',
    bodyColor: '#0f0f0f',
    scale: 2.55
  },
  {
    // 250ml slim can: scale ≈ 134/53 ≈ 2.53
    id: 'red-bull',
    targetImages: [
      'red-bull/wrap-01.jpg',
      'red-bull/wrap-02.jpg',
      'red-bull/wrap-03.jpg',
      'red-bull/wrap-04.jpg',
      'red-bull/wrap-05.jpg',
      'red-bull/wrap-06.jpg',
      'red-bull/wrap-07.jpg',
      'red-bull/wrap-08.jpg',
      'red-bull/wrap-09.jpg',
      'red-bull/wrap-10.jpg',
      'red-bull/wrap-11.jpg',
      'red-bull/wrap-12.jpg'
    ],
    name: 'Red Bull',
    flavour: 'Energy',
    calories: 113,
    volumeMl: 250,
    labelTexture: 'red-bull/wrapper.jpg',
    bodyColor: '#002776',
    scale: 2.53
  },
  {
    id: 'budweiser',
    targetImages: [
      'budweiser/wrap-01.jpg',
      'budweiser/wrap-02.jpg',
      'budweiser/wrap-03.jpg',
      'budweiser/wrap-04.jpg',
      'budweiser/wrap-05.jpg',
      'budweiser/wrap-06.jpg',
      'budweiser/wrap-07.jpg',
      'budweiser/wrap-08.jpg',
      'budweiser/wrap-09.jpg',
      'budweiser/wrap-10.jpg',
      'budweiser/wrap-11.jpg',
      'budweiser/wrap-12.jpg'
    ],
    name: 'Budweiser',
    flavour: 'Lager',
    calories: 145,
    volumeMl: 355,
    labelTexture: 'budweiser/wrapper.jpg',
    bodyColor: '#c8102e',
    scale: 1.74
  },
  {
    id: 'bud-light',
    targetImages: [
      'bud-light/wrap-01.jpg',
      'bud-light/wrap-02.jpg',
      'bud-light/wrap-03.jpg',
      'bud-light/wrap-04.jpg',
      'bud-light/wrap-05.jpg',
      'bud-light/wrap-06.jpg',
      'bud-light/wrap-07.jpg',
      'bud-light/wrap-08.jpg',
      'bud-light/wrap-09.jpg',
      'bud-light/wrap-10.jpg',
      'bud-light/wrap-11.jpg',
      'bud-light/wrap-12.jpg'
    ],
    name: 'Bud Light',
    flavour: 'Light Lager',
    calories: 110,
    volumeMl: 355,
    labelTexture: 'bud-light/wrapper.jpg',
    bodyColor: '#0033a0',
    scale: 1.74
  },
  {
    id: 'coors-light',
    targetImages: [
      'coors-light/wrap-01.jpg',
      'coors-light/wrap-02.jpg',
      'coors-light/wrap-03.jpg',
      'coors-light/wrap-04.jpg',
      'coors-light/wrap-05.jpg',
      'coors-light/wrap-06.jpg',
      'coors-light/wrap-07.jpg',
      'coors-light/wrap-08.jpg',
      'coors-light/wrap-09.jpg',
      'coors-light/wrap-10.jpg',
      'coors-light/wrap-11.jpg',
      'coors-light/wrap-12.jpg'
    ],
    name: 'Coors Light',
    flavour: 'Light Lager',
    calories: 102,
    volumeMl: 355,
    labelTexture: 'coors-light/wrapper.jpg',
    bodyColor: '#6d8ba3',
    scale: 1.74
  },
  {
    id: 'modelo-especial',
    targetImages: [
      'modelo-especial/wrap-01.jpg',
      'modelo-especial/wrap-02.jpg',
      'modelo-especial/wrap-03.jpg',
      'modelo-especial/wrap-04.jpg',
      'modelo-especial/wrap-05.jpg',
      'modelo-especial/wrap-06.jpg',
      'modelo-especial/wrap-07.jpg',
      'modelo-especial/wrap-08.jpg',
      'modelo-especial/wrap-09.jpg',
      'modelo-especial/wrap-10.jpg',
      'modelo-especial/wrap-11.jpg',
      'modelo-especial/wrap-12.jpg'
    ],
    name: 'Modelo',
    flavour: 'Especial',
    calories: 145,
    volumeMl: 355,
    labelTexture: 'modelo-especial/wrapper.jpg',
    bodyColor: '#c8a951',
    scale: 1.74
  },
  {
    id: 'michelob-ultra',
    targetImages: [
      'michelob-ultra/wrap-01.jpg',
      'michelob-ultra/wrap-02.jpg',
      'michelob-ultra/wrap-03.jpg',
      'michelob-ultra/wrap-04.jpg',
      'michelob-ultra/wrap-05.jpg',
      'michelob-ultra/wrap-06.jpg',
      'michelob-ultra/wrap-07.jpg',
      'michelob-ultra/wrap-08.jpg',
      'michelob-ultra/wrap-09.jpg',
      'michelob-ultra/wrap-10.jpg',
      'michelob-ultra/wrap-11.jpg',
      'michelob-ultra/wrap-12.jpg'
    ],
    name: 'Michelob Ultra',
    flavour: 'Light Lager',
    calories: 95,
    volumeMl: 355,
    labelTexture: 'michelob-ultra/wrapper.jpg',
    bodyColor: '#005596',
    scale: 1.74
  },
  {
    id: 'corona',
    targetImages: [
      'corona/wrap-01.jpg',
      'corona/wrap-02.jpg',
      'corona/wrap-03.jpg',
      'corona/wrap-04.jpg',
      'corona/wrap-05.jpg',
      'corona/wrap-06.jpg',
      'corona/wrap-07.jpg',
      'corona/wrap-08.jpg',
      'corona/wrap-09.jpg',
      'corona/wrap-10.jpg',
      'corona/wrap-11.jpg',
      'corona/wrap-12.jpg'
    ],
    name: 'Corona',
    flavour: 'Extra',
    calories: 148,
    volumeMl: 355,
    labelTexture: 'corona/wrapper.jpg',
    bodyColor: '#14294f',
    scale: 1.74
  },
  {
    // slim tall can, so scale is higher than a standard 330ml
    id: 'topo-chico-seltzer',
    targetImages: [
      'topo-chico-seltzer/wrap-01.jpg',
      'topo-chico-seltzer/wrap-02.jpg',
      'topo-chico-seltzer/wrap-03.jpg',
      'topo-chico-seltzer/wrap-04.jpg',
      'topo-chico-seltzer/wrap-05.jpg',
      'topo-chico-seltzer/wrap-06.jpg',
      'topo-chico-seltzer/wrap-07.jpg',
      'topo-chico-seltzer/wrap-08.jpg',
      'topo-chico-seltzer/wrap-09.jpg',
      'topo-chico-seltzer/wrap-10.jpg',
      'topo-chico-seltzer/wrap-11.jpg',
      'topo-chico-seltzer/wrap-12.jpg'
    ],
    name: 'Topo Chico',
    flavour: 'Hard Seltzer',
    calories: 100,
    volumeMl: 355,
    labelTexture: 'topo-chico-seltzer/wrapper.jpg',
    bodyColor: '#e8b800',
    scale: 2.3
  },
  {
    id: 'topo-chico-mineral',
    targetImages: [
      'topo-chico-mineral/wrap-01.jpg',
      'topo-chico-mineral/wrap-02.jpg',
      'topo-chico-mineral/wrap-03.jpg',
      'topo-chico-mineral/wrap-04.jpg',
      'topo-chico-mineral/wrap-05.jpg',
      'topo-chico-mineral/wrap-06.jpg',
      'topo-chico-mineral/wrap-07.jpg',
      'topo-chico-mineral/wrap-08.jpg',
      'topo-chico-mineral/wrap-09.jpg',
      'topo-chico-mineral/wrap-10.jpg',
      'topo-chico-mineral/wrap-11.jpg',
      'topo-chico-mineral/wrap-12.jpg'
    ],
    name: 'Topo Chico',
    flavour: 'Mineral Water',
    calories: 0,
    volumeMl: 355,
    labelTexture: 'topo-chico-mineral/wrapper.jpg',
    bodyColor: '#cfcfcf',
    scale: 2.3
  },
  /**
   * Topo Chico Sabores — sliced from the multipack box front (flat carton art),
   * so they track multi-angle like the other wrap cans. scale is a slim-can
   * estimate; tune by eye against a real can.
   */
  {
    id: 'topo-chico-mango',
    targetImages: [
      'topo-chico-mango/wrap-01.jpg',
      'topo-chico-mango/wrap-02.jpg',
      'topo-chico-mango/wrap-03.jpg',
      'topo-chico-mango/wrap-04.jpg',
      'topo-chico-mango/wrap-05.jpg',
      'topo-chico-mango/wrap-06.jpg',
      'topo-chico-mango/wrap-07.jpg',
      'topo-chico-mango/wrap-08.jpg',
      'topo-chico-mango/wrap-09.jpg',
      'topo-chico-mango/wrap-10.jpg',
      'topo-chico-mango/wrap-11.jpg',
      'topo-chico-mango/wrap-12.jpg'
    ],
    name: 'Topo Chico',
    flavour: 'Tropical Mango',
    calories: 0,
    volumeMl: 355,
    labelTexture: 'topo-chico-mango/wrapper.jpg',
    bodyColor: '#e0a83c',
    scale: 2.3
  },
  {
    id: 'topo-chico-blueberry',
    targetImages: [
      'topo-chico-blueberry/wrap-01.jpg',
      'topo-chico-blueberry/wrap-02.jpg',
      'topo-chico-blueberry/wrap-03.jpg',
      'topo-chico-blueberry/wrap-04.jpg',
      'topo-chico-blueberry/wrap-05.jpg',
      'topo-chico-blueberry/wrap-06.jpg',
      'topo-chico-blueberry/wrap-07.jpg',
      'topo-chico-blueberry/wrap-08.jpg',
      'topo-chico-blueberry/wrap-09.jpg',
      'topo-chico-blueberry/wrap-10.jpg',
      'topo-chico-blueberry/wrap-11.jpg',
      'topo-chico-blueberry/wrap-12.jpg'
    ],
    name: 'Topo Chico',
    flavour: 'Blueberry',
    calories: 0,
    volumeMl: 355,
    labelTexture: 'topo-chico-blueberry/wrapper.jpg',
    bodyColor: '#5b8fd0',
    scale: 2.3
  },
  {
    id: 'topo-chico-lime',
    targetImages: [
      'topo-chico-lime/wrap-01.jpg',
      'topo-chico-lime/wrap-02.jpg',
      'topo-chico-lime/wrap-03.jpg',
      'topo-chico-lime/wrap-04.jpg',
      'topo-chico-lime/wrap-05.jpg',
      'topo-chico-lime/wrap-06.jpg',
      'topo-chico-lime/wrap-07.jpg',
      'topo-chico-lime/wrap-08.jpg',
      'topo-chico-lime/wrap-09.jpg',
      'topo-chico-lime/wrap-10.jpg',
      'topo-chico-lime/wrap-11.jpg',
      'topo-chico-lime/wrap-12.jpg'
    ],
    name: 'Topo Chico',
    flavour: 'Lime with Mint',
    calories: 0,
    volumeMl: 355,
    labelTexture: 'topo-chico-lime/wrapper.jpg',
    bodyColor: '#8bc34a',
    scale: 2.3
  },
  {
    id: 'topo-chico-tangerine',
    targetImages: [
      'topo-chico-tangerine/wrap-01.jpg',
      'topo-chico-tangerine/wrap-02.jpg',
      'topo-chico-tangerine/wrap-03.jpg',
      'topo-chico-tangerine/wrap-04.jpg',
      'topo-chico-tangerine/wrap-05.jpg',
      'topo-chico-tangerine/wrap-06.jpg',
      'topo-chico-tangerine/wrap-07.jpg',
      'topo-chico-tangerine/wrap-08.jpg',
      'topo-chico-tangerine/wrap-09.jpg',
      'topo-chico-tangerine/wrap-10.jpg',
      'topo-chico-tangerine/wrap-11.jpg',
      'topo-chico-tangerine/wrap-12.jpg'
    ],
    name: 'Topo Chico',
    flavour: 'Tangerine with Ginger',
    calories: 0,
    volumeMl: 355,
    labelTexture: 'topo-chico-tangerine/wrapper.jpg',
    bodyColor: '#ef8c3a',
    scale: 2.3
  },
  {
    // flat art from the multipack box front, so it slices like the wrap cans
    id: 'topo-chico-raspberry',
    targetImages: [
      'topo-chico-raspberry/wrap-01.jpg',
      'topo-chico-raspberry/wrap-02.jpg',
      'topo-chico-raspberry/wrap-03.jpg',
      'topo-chico-raspberry/wrap-04.jpg',
      'topo-chico-raspberry/wrap-05.jpg',
      'topo-chico-raspberry/wrap-06.jpg',
      'topo-chico-raspberry/wrap-07.jpg',
      'topo-chico-raspberry/wrap-08.jpg',
      'topo-chico-raspberry/wrap-09.jpg',
      'topo-chico-raspberry/wrap-10.jpg',
      'topo-chico-raspberry/wrap-11.jpg',
      'topo-chico-raspberry/wrap-12.jpg'
    ],
    name: 'Topo Chico',
    flavour: 'Raspberry with Lemon',
    calories: 0,
    volumeMl: 355,
    labelTexture: 'topo-chico-raspberry/wrapper.jpg',
    bodyColor: '#d83f87',
    scale: 2.3
  }
]

/** directory holding target photos, relative to the project root */
export const targetsDir = 'public/targets'

export type TargetEntry = {
  can: Can
  /** path under public/targets, e.g. 'pepsi/wrap-01.jpg' */
  image: string
  /** which angle of that can this is, 1-based, for human-readable output */
  angle: number
}

/**
 * Every photo of every can, flattened. THIS is the compile order, and an
 * index into this array is a MindAR target index. Many entries map to one can.
 */
export const targetEntries: TargetEntry[] = cans.flatMap((can) =>
  can.targetImages.map((image, i) => ({ can, image, angle: i + 1 }))
)

/** browser-facing url for a can's label texture */
export const labelTextureUrl = (can: Can) =>
  `/targets/${can.labelTexture ?? can.targetImages[0] ?? ''}`

/** project-relative path the compiler script reads from disk */
export const targetImagePath = (image: string) => `${targetsDir}/${image}`

export const canByTargetIndex = (index: number): Can | undefined => targetEntries[index]?.can
